### ISSUE TITLE
Automatic CFG channels multipliers nodes do not appear in the ComfyUI interface

### ISSUE THREAD

**Issue by YanMednis** [Extraltodeus/ComfyUI-AutomaticCFG#17]
Hi! I'm encountering an issue with installing the Automatic CFG channels multipliers nodes from this repository. I've tried cloning the project via the command line (git clone) into the custom_nodes directory and also via the ComfyUI manager (using a Git URL). Other CFG nodes appear, but the Automatic CFG channels multipliers node is still missing.

Could anyone help me understand why it's not working? Perhaps there's a specific step I'm missing or something else that needs to be configured. Any assistance would be greatly appreciated!

**Comment by Extraltodeus** [comment]
Uh I guess you downloaded some old workflow? I don't even remember sharing such node but for sure I've done a few at least for myself. Just to try. 

Are you sure that it refers to this repository? If anything, just slap the simple auro cfg node in your workflow to try out

**Comment by YanMednis** [comment]
Thanks for the answer. Yes, you are right, I downloaded the workflow from this link https://comfyworkflows.com/workflows/8e351973-ffc4-4d1b-bc09-ee38ee655804 and replaced "Automatic CFG channels multipliers" with a simple auto CFG. But still getting the error, and I was hoping that I would find a solution in this node, but it seems the error is not related to it.

**Comment by Extraltodeus** [comment]
Actually I was wrong and I indeed shared this a while ago then removed it because I deemed it uninteresting. I guess I'll create a deprecated version in the future so to not create such issue. My apology!

If you want you can browse the older version of this repository and download as zip/extract in your custom nodes folder.

https://github.com/Extraltodeus/ComfyUI-AutomaticCFG/tree/126402d88474d4a02f77ba4ac407a613e821471a

If you give it a different name and remove this:

"Automatic CFG": simpleDynamicCFG,

from the __init__.py file it will make it not overwrite the recent version so you can use it without getting bothered!

**Comment by YanMednis** [comment]
Thank you so much for your work!
