### ISSUE TITLE
Discussions to further optimize

### ISSUE THREAD

**Issue by jax-explorer** [Extraltodeus/ComfyUI-AutomaticCFG#18]
It is very good to use off negative direction to improve the speed, theoretically it can be up to double the speed, then the remaining one crossAttention must go, if some scenarios also do not require positive direction

**Comment by Extraltodeus** [comment]
Not sure what you mean because my understanding of the attention mechanisms is quite intuitive rather than scholar. As far as my understanding goes, the cross attention relates more to your prompt while the self-attention relates more to pattern recognition. One aiming to create what you asked, the other aiming to create something coherent.

If intuitively what you may mean is that as some point of the sampling then the cross-attention feels like it's not needed anymore then I'd say from my experimental knowledge "maybe" because even the last few steps can help regarding the requested style such as characters not looking 3D rendered (as it is a common bias). So unless what you are prompting for is not contradictory with the model that you are using then cross attention is needed until it's not. And by "until it's not" I mean "until the style has been defined so much that the self-attention can carry on". Which is basically when I cut the negative. I'd also add that I am unsure at this stage how much, performance-wise, it would be useful to cut the cross attention.

I am currently experimenting deeper with the attention mechanism and am close to releasing an update which would allow to even time the modifications relatively to the sigmas but I need to be more clear myself about it.

If I got anything wrong then don't hesitate to detail further, I don't know much more than most people so I'm interested in your ideas!

**Comment by Extraltodeus** [comment]
I'm closing for the inactivity, don't hesitate to reopen if you want to add something!
